# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xtuner.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cxtuner.proto\x1a\x1bgoogle/protobuf/empty.proto\"r\n\rUploadRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\x12\x10\n\x08tunnable\x18\x03 \x03(\t\x12\x0e\n\x06\x63onfig\x18\x04 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x05 \x01(\x05\x12\x10\n\x08hostName\x18\x06 \x01(\t\"\x1d\n\x0bUploadReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"=\n\x0b\x44\x65\x62ugLogMsg\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x10\n\x08hostName\x18\x03 \x01(\t2r\n\x06Xtuner\x12/\n\rUploadMetrics\x12\x0e.UploadRequest\x1a\x0c.UploadReply\"\x00\x12\x37\n\rPrintDebugMsg\x12\x0c.DebugLogMsg\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xtuner_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UPLOADREQUEST._serialized_start=45
  _UPLOADREQUEST._serialized_end=159
  _UPLOADREPLY._serialized_start=161
  _UPLOADREPLY._serialized_end=190
  _DEBUGLOGMSG._serialized_start=192
  _DEBUGLOGMSG._serialized_end=253
  _XTUNER._serialized_start=255
  _XTUNER._serialized_end=369
# @@protoc_insertion_point(module_scope)
