# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import xtuner_pb2 as xtuner__pb2


class XtunerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadMetrics = channel.unary_unary(
                '/Xtuner/UploadMetrics',
                request_serializer=xtuner__pb2.UploadRequest.SerializeToString,
                response_deserializer=xtuner__pb2.UploadReply.FromString,
                )
        self.PrintDebugMsg = channel.unary_unary(
                '/Xtuner/PrintDebugMsg',
                request_serializer=xtuner__pb2.DebugLogMsg.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class XtunerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrintDebugMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XtunerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadMetrics,
                    request_deserializer=xtuner__pb2.UploadRequest.FromString,
                    response_serializer=xtuner__pb2.UploadReply.SerializeToString,
            ),
            'PrintDebugMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.PrintDebugMsg,
                    request_deserializer=xtuner__pb2.DebugLogMsg.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Xtuner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Xtuner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Xtuner/UploadMetrics',
            xtuner__pb2.UploadRequest.SerializeToString,
            xtuner__pb2.UploadReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrintDebugMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Xtuner/PrintDebugMsg',
            xtuner__pb2.DebugLogMsg.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
